### ISSUE TITLE
java.sql.SQLException: Unable to run insert stmt on object me.confuser.banmanager.data.

### ISSUE THREAD

**Issue by Spirit55555** [confuser/Ban-Management#130]
I have just converted my database and I got this error in the process. The conversion did continue, so it's not a major bug.

https://gist.github.com/Spirit55555/421dfe9503407a9be69a

**Comment by frdmn** [comment]
@Spirit55555 Since `id` is the primary key, no duplicates are allowed in this SQL table. Apparently you have two times the same UUID associated to different playernames in your old database, even though i'm not sure how that happend. Do you run a offline-mode server that does any UUID adjuments/hacks?

**Comment by Spirit55555** [comment]
Yes, I run Spigot in offline mode with a BungeeCord proxy.

**Comment by confuser** [comment]
There is a rare case that was reported to Mojang quite some time ago that a multiple names were associated with the same UUID. It is possible this is the case, but highly unlikely. Could you confirm though, for sanity sakes in case there is a bug in the conversion process?

**Comment by confuser** [comment]
@Spirit55555 please re-open if you are able to confirm the cause.
