### ISSUE TITLE
Possible alts inaccurate?

### ISSUE THREAD

**Issue by Theepwner** [confuser/Ban-Management#139]
I've recently converted to v5 using build 43.  The only noticeable issue is that using /alts (name) will show a lot of players as possible alts, thinking that they all have the localhost ip, 127.0.0.1

This also goes for using /bminfo and having the correct perms.  http://i.imgur.com/zOjNVSp.jpg

I believe it isn't showing all banned players as being alts though, which makes this issue a bit odd.  Also, this is through bungeecord, but I have properly enabled ip forwarding.

**Comment by confuser** [comment]
There are two scenarios when this occurs.

Firstly when a player has been banned, warned, or muted, but hasn't joined the server since BanManager was installed, it'll default their ip address to 127.0.0.1 in the database.

Secondly, during the conversion process, if no player ip is stored for that player, it'll also default to 127.0.0.1.
